### ISSUE TITLE
Kubernetes Redis 3.2 protected mode 

### ISSUE THREAD

**Issue by michaelschefczyk** [sickp/docker-alpine-redis#2]
Dear Adrian,

Thank you very much for publishing docker-alpine-redis! I am trying to fight the problem of Redis 3.2 containers running under Kubernetes to stop working because of the protected mode issue (my initial attempts described here https://groups.google.com/forum/#!topic/redis-db/wFfXl8hAM98).

Even when I run your (super compact!) image docker.io/sickp/alpine-redis   latest-k8s          78ab50f832ac (tagged as dockers10a:5000/redis:latest in my cluster) and telnet to it, I do get the "Redis is running in protected mode ..." response. Could you please be so kind to point me to what I am doing wrong?

Thank you very much!

Michael

P.S.: My replication controller (working with no issues with any Redis 3.0.7 image) is:

apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-controller
spec:
  replicas: 1
  selector:
    name: redis
  template:
    spec:
      volumes:
        - name: redisnfs
          nfs:
            server: 192.168.1.61
            path: "/redis"
      containers:
        - name: redis
          image: dockers10a:5000/redis:latest
          command: ["redis-server","--appendonly yes"]
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redisnfs
              mountPath: "/data"
          securityContext:
            privileged: true
      nodeSelector:
        location: DRS
    metadata:
      labels:
        name: redis

**Comment by sickp** [comment]
Have you connected to the running pod and verified that `/etc/redis.conf` contains `bind 0.0.0.0`? (And of course that `redis-server` is started using the `/etc/redis.conf` configuration and not some default or other)?

```bash
kubectl exec -it your-node-name grep bind /etc/redis.conf
...
bind 0.0.0.0
```

 According to the Redis config file comments, explicitly `bind` should disable protected mode.

**Comment by michaelschefczyk** [comment]
Thank you very much for looking into this issue! The container does seem to run in protected mode even if the the config file actually used contains bind 0.0.0.0. To that extent, the output of Redis 3.2 given via telnet is misleading, I think, as it suggests that this would solve it.

What does help, however, is to change line 19 in the controller config above to:

          command: ["redis-server","--appendonly yes","--protected-mode no"]

**Comment by sickp** [comment]
Ah, that's the problem. You're running without a configuration file. The first argument to `redis-server` should be the path of your configuration file.

The reason why the `sickp/alpine-redis` image isn't working is because you are overriding it's default command:

```
command: ["redis-server", "/etc/redis.conf"]
```

and replacing it with one that causes Redis to auto-generate a default config, then explicitly setting `appendonly yes` over it.
